apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: erp-elastic
  namespace: default
spec:
  version: 8.12.0
  nodeSets:
    - name: local-node
      count: 1
      config:
        node.roles: ["master", "data", "ingest"]
        xpack.security.enabled: true
        xpack.security.http.ssl.enabled: true
        xpack.security.transport.ssl.enabled: true
      podTemplate:
        spec:
          containers:
            - name: elasticsearch
              resources:
                requests:
                  memory: "768Mi"
                  cpu: "200m"
                limits:
                  memory: "1Gi"
              env:
                - name: ES_JAVA_OPTS
                  value: "-Xms512m -Xmx512m"
      volumeClaimTemplates:
        - metadata:
            name: elasticsearch-data
          spec:
            accessModes: ["ReadWriteOnce"]
            resources:
              requests:
                storage: 2Gi
